services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  system:
    build:
      context: ./system/
      dockerfile: Dockerfile
      args:
        PROJECT_PATH: ${WORKDIR}
    container_name: dev-system
    environment:
      - PROJECT_REPO=${PROJECT_REPO}
      - WORKDIR=${WORKDIR}
      - DISPLAY=${DISPLAY:-:0}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    group_add:
      - audio
      - video
    network_mode: host
    command: sleep infinity
 
